on:
  push:
    branches:
      - 'release/**'
  pull_request:
    branches:
      - 'release/**'
    paths:
      - prog_models

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
        python -m pip install notebook
        python -m pip install testbook
        python -m pip install requests
    - name: Run tests
      run: python -m tests